/**
 * Redirect maps for the move from the legacy Total Transport Team website on
 * totaltransportteam.co.uk to House Moving Experts on housemovingexperts.com.
 *
 * This is a CROSS-DOMAIN migration, so there are two redirect files to deploy,
 * in two different places:
 *
 *   1. public/_redirects — ships with THIS site, on the new domain. Handles
 *      path-level consolidations for anyone who lands on an old path here.
 *
 *   2. redirects/legacy-domain/_redirects — must be deployed on the OLD domain,
 *      totaltransportteam.co.uk. Every rule is an absolute URL pointing at the
 *      new domain. This is the file that actually carries the search equity
 *      across; without it the rebrand starts from zero authority.
 *
 * Both are generated by `bun run seo:generate`. Edit here, not the output.
 *
 * IMPORTANT: the legacy URL inventory below was assembled from search-engine
 * results for the live domain, because the old site itself was not reachable
 * from the build environment. Before go-live, export the full URL list from
 * Google Search Console (Pages report) and server logs and reconcile it with
 * this map — see docs/seo-migration.md.
 */

export type RedirectRule = {
  from: string;
  /** Where it goes. `null` means the page is retired with no relevant equivalent. */
  to: string | null;
  /** Why — kept so the map can be reviewed rather than trusted blindly. */
  note: string;
};

/**
 * Legacy removals URLs whose PATH is unchanged on the new domain.
 *
 * These are the valuable ones. Because the path is identical, the old-domain
 * redirect is a clean one-to-one hop to the same path on the new domain — the
 * strongest signal to Google that the page simply moved house, rather than
 * being replaced by something vaguely similar.
 */
export const preservedPaths: string[] = [
  "/",
  "/house-removals",
  "/house-removals/slough",
  "/office-removals",
  "/commercial-moving",
  "/local-removals",
  "/long-distance-moving",
  "/international-moving",
  "/packing-and-unpacking-services",
  "/storage-services",
  "/about",
  "/contact",
];

/**
 * Consolidations — a legacy removals page whose content now lives inside a
 * broader page. These keep their equity by pointing at a genuinely relevant
 * replacement.
 */
export const consolidations: RedirectRule[] = [
  {
    from: "/warehouse-moving",
    to: "/commercial-moving",
    note: "Warehouse moves are now covered within Commercial Removals to keep consumer navigation simple.",
  },
  {
    from: "/man-van-services",
    to: "/local-removals",
    note: "Man-and-van enquiries are short local moves — Local Removals is the closest genuine equivalent.",
  },
  {
    from: "/moving-services",
    to: "/services",
    note: "Legacy services hub → new removals services hub.",
  },
  {
    from: "/services/house-removals",
    to: "/house-removals",
    note: "Defensive: any nested variant of the house removals URL.",
  },
  {
    from: "/quote-request",
    to: "/quote",
    note: "Legacy enquiry form → new multi-step quote flow.",
  },
  {
    from: "/get-a-quote",
    to: "/quote",
    note: "Legacy quote URL variant.",
  },
];

/**
 * Retired legacy transport services.
 *
 * The business no longer markets these, and there is no removals page that genuinely
 * matches the intent behind them — someone searching for breakdown recovery is
 * not looking for a removals company. Redirecting them all to the homepage
 * would create soft 404s on a brand-new domain that has no authority to spare,
 * so they are retired instead.
 *
 * Preferred handling is HTTP 410 Gone where the host supports it; the
 * generated _redirects file falls back to 404 on hosts that don't.
 */
export const retiredUrls: RedirectRule[] = [
  { from: "/vehicle-transport-recovery", to: null, note: "Legacy vehicle transport / recovery." },
  { from: "/car-recovery", to: null, note: "Legacy car recovery." },
  { from: "/car-transport", to: null, note: "Legacy car transport." },
  { from: "/roadside-assistance", to: null, note: "Legacy roadside assistance." },
  { from: "/jump-start-services", to: null, note: "Legacy jump start services." },
  { from: "/breakdown-recovery/*", to: null, note: "Legacy breakdown recovery local pages." },
  { from: "/courier-services", to: null, note: "Legacy courier services." },
  { from: "/pallet-delivery", to: null, note: "Legacy pallet delivery." },
  { from: "/executive-travel", to: null, note: "Legacy executive travel / chauffeur hire." },
  { from: "/chauffeur-hire", to: null, note: "Legacy chauffeur hire." },
  { from: "/airport-transfers", to: null, note: "Legacy airport transfers." },
  { from: "/limousine-hire", to: null, note: "Legacy limousine hire." },
];

export const allRules: RedirectRule[] = [...consolidations, ...retiredUrls];
