/**
 * Generates public/sitemap.xml, public/robots.txt and public/_redirects from
 * the site's configuration, so the three never drift out of sync with the
 * routes.
 *
 * Run with:  bun run seo:generate
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

import { areas } from "../src/config/areas";
import { business } from "../src/config/business";
import { consolidations, retiredUrls } from "../src/config/redirects";
import { services } from "../src/config/services";

const publicDir = join(import.meta.dir, "..", "public");

type SitemapEntry = { path: string; priority: string; changefreq: string };

const entries: SitemapEntry[] = [
  { path: "/", priority: "1.0", changefreq: "weekly" },
  { path: "/quote", priority: "0.9", changefreq: "monthly" },
  { path: "/services", priority: "0.8", changefreq: "monthly" },
  ...services.map((service) => ({
    path: `/${service.slug}`,
    priority: service.category === "removals" ? "0.9" : "0.8",
    changefreq: "monthly",
  })),
  { path: "/areas-we-cover", priority: "0.7", changefreq: "monthly" },
  ...areas.map((area) => ({
    path: `/house-removals/${area.slug}`,
    priority: "0.7",
    changefreq: "monthly",
  })),
  { path: "/about", priority: "0.6", changefreq: "yearly" },
  { path: "/reviews", priority: "0.6", changefreq: "monthly" },
  { path: "/contact", priority: "0.7", changefreq: "yearly" },
  { path: "/privacy-policy", priority: "0.2", changefreq: "yearly" },
  { path: "/cookie-policy", priority: "0.2", changefreq: "yearly" },
  { path: "/terms-and-conditions", priority: "0.2", changefreq: "yearly" },
];

const today = new Date().toISOString().slice(0, 10);

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map((entry) =>
    [
      "  <url>",
      `    <loc>${business.siteUrl}${entry.path === "/" ? "/" : entry.path}</loc>`,
      `    <lastmod>${today}</lastmod>`,
      `    <changefreq>${entry.changefreq}</changefreq>`,
      `    <priority>${entry.priority}</priority>`,
      "  </url>",
    ].join("\n"),
  )
  .join("\n")}
</urlset>
`;

const robots = `# ${business.brandName} — ${business.brandExpanded}
User-agent: *
Allow: /

Sitemap: ${business.siteUrl}/sitemap.xml
`;

const redirects = `# Generated by scripts/generate-seo-files.ts — edit src/config/redirects.ts instead.
#
# Consolidated legacy removals URLs (301 — equity passes to the new page).
${consolidations.map((rule) => `${rule.from}  ${rule.to}  301`).join("\n")}

# Retired legacy transport services. TTT is a removals company and there is no
# genuinely relevant replacement for these, so they are gone rather than
# redirected to an unrelated page (which would be a soft 404).
# Prefer HTTP 410 where the host supports it — see docs/seo-migration.md.
${retiredUrls.map((rule) => `${rule.from}  /404  404`).join("\n")}
`;

writeFileSync(join(publicDir, "sitemap.xml"), sitemap);
writeFileSync(join(publicDir, "robots.txt"), robots);
writeFileSync(join(publicDir, "_redirects"), redirects);

console.log(`Wrote sitemap.xml (${entries.length} URLs), robots.txt and _redirects.`);
