/**
 * Generates the site's SEO files from configuration, so they never drift out of
 * sync with the routes:
 *
 *   public/sitemap.xml                  — every route on the new domain
 *   public/robots.txt
 *   public/_redirects                   — path consolidations, new domain
 *   redirects/legacy-domain/_redirects  — DEPLOY ON totaltransportteam.co.uk
 *
 * The last one is the important one for the rebrand: it is what carries the old
 * domain's search equity to the new one. It is written outside public/ on
 * purpose — it must not ship with this site.
 *
 * Run with:  bun run seo:generate
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { areas } from "../src/config/areas";
import { business } from "../src/config/business";
import { consolidations, preservedPaths, retiredUrls } from "../src/config/redirects";
import { services } from "../src/config/services";

const publicDir = join(import.meta.dir, "..", "public");
const legacyDir = join(import.meta.dir, "..", "redirects", "legacy-domain");

type SitemapEntry = { path: string; priority: string; changefreq: string };

const entries: SitemapEntry[] = [
  { path: "/", priority: "1.0", changefreq: "weekly" },
  { path: "/quote", priority: "0.9", changefreq: "monthly" },
  { path: "/services", priority: "0.8", changefreq: "monthly" },
  ...services.map((service) => ({
    path: `/${service.slug}`,
    priority: service.category === "removals" ? "0.9" : "0.8",
    changefreq: "monthly",
  })),
  { path: "/areas-we-cover", priority: "0.7", changefreq: "monthly" },
  ...areas.map((area) => ({
    path: `/house-removals/${area.slug}`,
    priority: "0.7",
    changefreq: "monthly",
  })),
  { path: "/about", priority: "0.6", changefreq: "yearly" },
  { path: "/reviews", priority: "0.6", changefreq: "monthly" },
  { path: "/contact", priority: "0.7", changefreq: "yearly" },
  { path: "/privacy-policy", priority: "0.2", changefreq: "yearly" },
  { path: "/cookie-policy", priority: "0.2", changefreq: "yearly" },
  { path: "/terms-and-conditions", priority: "0.2", changefreq: "yearly" },
];

const today = new Date().toISOString().slice(0, 10);

const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries
  .map((entry) =>
    [
      "  <url>",
      `    <loc>${business.siteUrl}${entry.path === "/" ? "/" : entry.path}</loc>`,
      `    <lastmod>${today}</lastmod>`,
      `    <changefreq>${entry.changefreq}</changefreq>`,
      `    <priority>${entry.priority}</priority>`,
      "  </url>",
    ].join("\n"),
  )
  .join("\n")}
</urlset>
`;

const robots = `# ${business.brandName} — ${business.companyName}
User-agent: *
Allow: /

Sitemap: ${business.siteUrl}/sitemap.xml
`;

// --- New domain: path-level consolidations only -----------------------------
const redirects = `# Generated by scripts/generate-seo-files.ts — edit src/config/redirects.ts instead.
# Deployed with THIS site, on ${business.siteUrl}.
#
# Consolidated legacy removals paths (301 — equity passes to the new page).
${consolidations.map((rule) => `${rule.from}  ${rule.to}  301`).join("\n")}

# Retired legacy transport services. This is a removals company and there is no
# genuinely relevant replacement for these, so they are gone rather than
# redirected to an unrelated page (which would be a soft 404).
# Prefer HTTP 410 where the host supports it — see docs/seo-migration.md.
${retiredUrls.map((rule) => `${rule.from}  /404  404`).join("\n")}
`;

// --- Legacy domain: absolute 301s onto the new domain ------------------------
// This file does the actual work of the rebrand. Every surviving legacy URL
// gets a one-to-one hop so Google can transfer the ranking signals.
const legacyRedirects = `# Generated by scripts/generate-seo-files.ts — edit src/config/redirects.ts instead.
#
# DEPLOY THIS ON THE OLD DOMAIN (${business.legacyDomain}), NOT with the new site.
#
# It 301s every legacy URL onto ${business.siteUrl}. Without it, the rebrand
# throws away the search equity the business has built up. Keep the old domain
# registered and serving these redirects for at least a year after launch, and
# file a Change of Address in Google Search Console.

# Same path, new domain — the strongest possible migration signal.
${preservedPaths
  .map((path) => {
    const from = path === "/" ? "/" : path;
    const to = path === "/" ? `${business.siteUrl}/` : `${business.siteUrl}${path}`;
    return `${from}  ${to}  301`;
  })
  .join("\n")}

# Consolidated onto a broader page on the new domain.
${consolidations.map((rule) => `${rule.from}  ${business.siteUrl}${rule.to}  301`).join("\n")}

# Retired — no relevant equivalent on the new site. Prefer 410 where supported.
${retiredUrls.map((rule) => `${rule.from}  /404  404`).join("\n")}

# Catch-all: anything not listed above still reaches the new homepage rather
# than dying, but every URL worth keeping should be given an explicit rule
# above instead of relying on this line.
/*  ${business.siteUrl}/  301
`;

mkdirSync(legacyDir, { recursive: true });

writeFileSync(join(publicDir, "sitemap.xml"), sitemap);
writeFileSync(join(publicDir, "robots.txt"), robots);
writeFileSync(join(publicDir, "_redirects"), redirects);
writeFileSync(join(legacyDir, "_redirects"), legacyRedirects);

console.log(
  `Wrote sitemap.xml (${entries.length} URLs), robots.txt, public/_redirects and ` +
    `redirects/legacy-domain/_redirects (${preservedPaths.length + consolidations.length} 301s).`,
);
